[package]
name = "BuckyDaemon"
version = "0.1.0"
authors = ["TheOpenDevProject <tkgs28@gmail.com>"]
[dependencies]
lettre = "0.5.0"
tiny_http = "0.5.1"
rustorm = "0.3.2"
mongodb = "0.1.1"
serde_json = "0.6.0"
